// Generated by CoffeeScript 1.12.4
(function() {
  var app;

  app = angular.module("myApp");

  app.controller("baseCtrl", function($scope, $rootScope) {
    $rootScope.title = "Index";
    $rootScope.small = "";
    $rootScope.items = [];
    return $rootScope.active_item = "Index";
  });

}).call(this);
