// Generated by CoffeeScript 1.12.4
(function() {
  var app;

  app = angular.module("myApp", ['ui.router', "ngResource"]);

  app.config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise("/");
    return $stateProvider.state('index', {
      url: "/",
      templateUrl: "templates/index.html",
      controller: "indexCtrl"
    }).state('edit', {
      url: "/edit",
      templateUrl: "templates/edit.html",
      controller: "indexCtrl"
    }).state('register', {
      url: "/register",
      templateUrl: "templates/register.html",
      controller: "registerCtrl"
    });
  });

}).call(this);
